# Hexo Configuration
# Site
title: 喜欢张诗雨
subtitle: ''
description: ''
keywords:
author: Dew
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://nosedewdrop.github.io/project'

permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks


